# .github/workflows/build-linux.yml
# Last modified: 18-Apr-2025 (kobayasy)

name: Linux

on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build and install
      run: |
        mkdir build
        cd build
        ../src/configure --prefix=$HOME --enable-warnall
        make install distclean
        cd ..
        rmdir build
    - name: Run
      run: |
        mkdir -m700 ~/pSync
        echo 'psync pSync' > ~/.psync.conf
        chmod 600 ~/.psync.conf
        ~/bin/psync --help
