# .github/workflows/build.yml - Last modified: 13-Jun-2021 (kobayasy)

name: Build

on:
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        dist:
          - psync-2.4
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Build
        run: test -e ${{ matrix.dist }} || tar xzf ${{ matrix.dist }}.tar.gz
      - name: Build and install
        run: cd ${{ matrix.dist }} && ./configure --prefix=$HOME && make install distclean
      - name: Run
        run: mkdir -m700 ~/pSync && echo 'psync pSync' > ~/.psync.conf && chmod 600 ~/.psync.conf && ~/bin/psync --help
