# .github/workflows/build-windows.yml
# Last modified: 29-Mar-2023 (kobayasy)

name: Windows

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        install: make gcc ncurses-devel
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build and install
      run: |
        mkdir build
        cd build
        ../src/configure --prefix=$HOME --enable-warnall
        make install distclean
        cd ..
        rmdir build
    - name: Run
      run: |
        mkdir ~/pSync
        echo 'psync pSync' > ~/.psync.conf
        ~/bin/psync --help
